### ISSUE TITLE
provide an example for the value to be passed to "filter" query parameter while calling "List directory exports"

### ISSUE THREAD

**Issue by kishore-hashedin** [PureStorage-OpenConnect/py-pure-client#3]
It is not clear what value can be provided to the "filter" query parameter while calling "List directory exports". For example, I want to filter all directory exports which are of policy.resource_type=policies/nfs. How can I achieve this using filter?

**Comment by tiberiuvs** [comment]
Detailed filtering syntax with examples is described in https://support.purestorage.com/Pure1/Pure1_Manage/Pure1_Manage_-_REST_API/Pure1_Manage_-_REST_API__Reference
