### ISSUE TITLE
Missing cleanup of allocated API client resources by the Client method

### ISSUE THREAD

**Issue by genegr** [PureStorage-OpenConnect/py-pure-client#34]
See PR #33

**Comment by Gregory-Bessonov** [comment]
Hi @genegr,

Thank you for submitting PR! We added that functionality in [version 1.23.0](https://github.com/PureStorage-OpenConnect/py-pure-client/releases/tag/1.38.0) and slightly improved it in [version 1.38.0](https://github.com/PureStorage-OpenConnect/py-pure-client/releases/tag/1.38.0)
