### ISSUE TITLE
Pinned paramiko version causes blowfish cryptography warnings

### ISSUE THREAD

**Issue by gtfortytwo** [PureStorage-OpenConnect/py-pure-client#41]
There was a semi-recent update to the `cryptography` package which caused users of the `paramiko` package to receive [warnings about deprecation of the `blowfish` algorithm](https://github.com/paramiko/paramiko/issues/2038) on every execution.  There are workarounds, but must explicitly configure the default ciphers or disable warnings to remove this message.

The `paramiko` project released a `2.11.0` which addresses the issue, but this `py-pure-client` package's `requirements.txt` currently pins the `parmiko` package to the exact version `2.10.1`.  I'd be surprised if there's genuinely a conflict with using `2.11`.  Could this project be updated to pick up the >= `2.11` release of `paramiko`?  In the meantime we are able to work around it by forcing `paramiko` to `2.11.0`, but always with unresolvable dependency complaints.

**Comment by Gregory-Bessonov** [comment]
Hi @gtfortytwo,
Dependencies for py-pure-client was reviewed and updated in [version 1.32.0](https://github.com/PureStorage-OpenConnect/py-pure-client/releases/tag/1.32.0). Now it requires `paramiko >=2.11.0, <= 2.12.0`

Please let us know if you have any questions or comments.

Thank you!
