### ISSUE TITLE
Increase supported version of `requests`

### ISSUE THREAD

**Issue by macwinnie** [PureStorage-OpenConnect/py-pure-client#64]
For DCIM automation, it's necessary to run `py-pure-client` together with `pynautobot` in our setup.

```
The conflict is caused by:
    The user requested requests
    pynautobot 1.5.0 depends on requests<3.0.0 and >=2.30.0
    py-pure-client 1.38.0 depends on requests<=2.28.1 and >=2.20.1
```

Please release an update to support at least full v2 of `requests` package!
Thanks a lot!

**Comment by Gregory-Bessonov** [comment]
Hello [macwinnie](https://github.com/macwinnie),

It is a perfect timing as we planned to update list of versions of dependencies in the one of the next releases. Versions will be updated for requests and setuptools.

Thank you for notifying us!

**Comment by Gregory-Bessonov** [comment]
py-pure-client@1.39.0 has support of requests up to 2.31.0. It should resolve the issue.
