### ISSUE TITLE
Increase the version of paramiko dependency

### ISSUE THREAD

**Issue by dturecekps** [PureStorage-OpenConnect/py-pure-client#72]
Would it be possible to increase the version of paramiko dependency to 3.X.X ?

**Comment by dturecekps** [comment]
There is not. It was just to update to latest version. We can live with 2.x for now

**Comment by Gregory-Bessonov** [comment]
@dturecekps, in py-pure-client@1.46.0 upper limit on versions of dependencies was removed. Please let us know if it solved original issue.
Thank you!

**Comment by sdodsley** [comment]
If we stick with 2.x then we break OpenStack as we move towards REST 2 support in our Cinder driver. 
The removal of the upper limit has allowed us to pass dependency tests and move forward with the migration to REST 2 for the Cinder driver.

**Comment by dturecekps** [comment]
We're good. thank you
